const fs = require("fs");
const dir = "C:\\Users\\19927\\tg-duel-game\\src\\games\\";

// High/Low
fs.writeFileSync(dir+"highlow.js", "// 🎲 猜大小\nconst{v4}=require(\"uuid\");const g=new Map();const D=[\"\",\"⚀\",\"⚁\",\"⚂\",\"⚃\",\"⚄\",\"⚅\"];\nmodule.exports={id:\"highlow\",name:\"🎲 猜大小\",async startPlay(ctx){\nconst l=(ctx.from?.language_code||\"\").startsWith(\"zh\")?\"zh\":\"en\";const id=v4().slice(0,6);\nconst f=Math.floor(Math.random()*6)+1;g.set(id,{id,lang:l,first:f});\nawait ctx.reply(l===\"zh\"?(\"🎲 猜大小\\n\\n当前：\"+D[f]+\" \"+f+\"\\n\\n下一个会比\"+f+\"高还是低？\"):(\"🎲 High/Low\\n\\nCurrent: \"+D[f]+\" \"+f+\"\\n\\nHigher or Lower?\"),\n{reply_markup:{inline_keyboard:[[{text:\"⬆️ \"+(l===\"zh\"?\"高\":\"HIGH\"),callback_data:\"game_highlow_bet_\"+id+\"_high\"},{text:\"⬇️ \"+(l===\"zh\"?\"低\":\"LOW\"),callback_data:\"game_highlow_bet_\"+id+\"_low\"}]]}});},\nasync handleCallback(ctx,action){\nconst p=action.split(\"_\");const id=p[0];const bet=p[1];const gg=g.get(id);if(!gg)return ctx.answerCbQuery(\"❌\");\nconst sec=Math.floor(Math.random()*6)+1;const win=(bet===\"high\"&&sec>gg.first)||(bet===\"low\"&&sec<gg.first);\nconst tie=sec===gg.first;let msg;\nif(gg.lang===\"zh\"){if(tie)msg=\"🎲 平局！都是\"+gg.first;else if(win)msg=\"🎉 你赢了！\"+gg.first+\" → \"+sec;else msg=\"😅 你输了！\"+gg.first+\" → \"+sec;\n}else{if(tie)msg=\"🎲 Tie! Both \"+gg.first;else if(win)msg=\"🎉 You win! \"+gg.first+\" → \"+sec;else msg=\"😅 You lose! \"+gg.first+\" → \"+sec;}\nawait ctx.editMessageText(msg,{reply_markup:{inline_keyboard:[[{text:\"🎲 \"+(gg.lang===\"zh\"?\"再来一局\":\"PLAY AGAIN\"),callback_data:\"game_highlow_new\"}]]}});\ng.delete(id);return ctx.answerCbQuery(win?\"🎉\":\"😅\");}};");
console.log("highlow: OK");

// Dragon Tiger
fs.writeFileSync(dir+"dragontiger.js", "// 🃏 龙虎斗\nconst{v4}=require(\"uuid\");const g=new Map();\nconst C=[\"🂡\",\"🂢\",\"🂣\",\"🂤\",\"🂥\",\"🂦\",\"🂧\",\"🂨\",\"🂩\",\"🂪\",\"🂫\",\"🂭\",\"🂮\"];const V=[14,2,3,4,5,6,7,8,9,10,11,12,13];\nmodule.exports={id:\"dragontiger\",name:\"🃏 龙虎斗\",async startPlay(ctx){\nconst l=(ctx.from?.language_code||\"\").startsWith(\"zh\")?\"zh\":\"en\";const id=v4().slice(0,6);g.set(id,{id,lang:l});\nawait ctx.reply(l===\"zh\"?\"🃏 龙虎斗\\n\\n押龙还是虎？\":\"🃏 Dragon Tiger\\n\\nBet on Dragon or Tiger?\",\n{reply_markup:{inline_keyboard:[[{text:\"🐉 \"+(l===\"zh\"?\"龙\":\"DRAGON\"),callback_data:\"game_dragontiger_bet_\"+id+\"_dragon\"},{text:\"🐯 \"+(l===\"zh\"?\"虎\":\"TIGER\"),callback_data:\"game_dragontiger_bet_\"+id+\"_tiger\"}]]}});},\nasync handleCallback(ctx,action){\nconst p=action.split(\"_\");const id=p[0];const bet=p[1];const gg=g.get(id);if(!gg)return ctx.answerCbQuery(\"❌\");\nconst dc=C[Math.floor(Math.random()*13)],tc=C[Math.floor(Math.random()*13)];const dv=V[C.indexOf(dc)],tv=V[C.indexOf(tc)];\nlet winner=\"tie\";if(dv>tv)winner=\"dragon\";else if(tv>dv)winner=\"tiger\";\nconst win=(bet===winner);let msg;\nif(gg.lang===\"zh\"){msg=\"🃏 龙虎斗\\n\\n🐉 龙：\"+dc+\"\\n🐯 虎：\"+tc+\"\\n\\n\";if(winner===\"tie\")msg+=\"🤝 平局！\";else if(win)msg+=\"🎉 你赢了！\";else msg+=\"😅 你输了！\";\n}else{msg=\"🃏 Dragon Tiger\\n\\n🐉 Dragon: \"+dc+\"\\n🐯 Tiger: \"+tc+\"\\n\\n\";if(winner===\"tie\")msg+=\"🤝 Tie!\";else if(win)msg+=\"🎉 You win!\";else msg+=\"😅 You lose!\";}\nawait ctx.editMessageText(msg,{reply_markup:{inline_keyboard:[[{text:\"🃏 \"+(gg.lang===\"zh\"?\"再来一局\":\"PLAY AGAIN\"),callback_data:\"game_dragontiger_new\"}]]}});\ng.delete(id);return ctx.answerCbQuery(win?\"🎉\":\"😅\");}};");
console.log("dragontiger: OK");

// Verify
try{require(dir+"highlow.js");console.log("highlow LOADED")}catch(e){console.log("highlow FAIL:"+e.message)}
try{require(dir+"dragontiger.js");console.log("dragontiger LOADED")}catch(e){console.log("dragontiger FAIL:"+e.message)}
try{require(dir+"slots.js");console.log("slots LOADED")}catch(e){console.log("slots FAIL:"+e.message)}
